'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { Archive as ArchiveIcon, ArrowUpRight, BookOpen, Check, FileText, Film, FolderOpen, ImageIcon, Inbox, Link2, Loader2, Music2, Plus, Search, Smile, Upload, X, Download, Trash2,  } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from '@/components/ui/sheet';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Checkbox } from '@/components/ui/checkbox';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Empty, EmptyHeader, EmptyTitle, EmptyDescription, EmptyMedia } from '@/components/ui/empty';
import { Skeleton } from '@/components/ui/skeleton';
import { AlertDialog, AlertDialogContent, AlertDialogHeader, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogCancel, AlertDialogAction } from '@/components/ui/alert-dialog';
import { Toaster } from '@/components/ui/sonner';
import { toast } from 'sonner';
import { destinations, inferKind, Item, kinds, suggest } from '@/lib/archive';
const icons:Record<string,typeof Link2>={Article:BookOpen,Video:Film,GIF:Smile,Meme:Smile,Image:ImageIcon,Audio:Music2,Document:FileText,Link:Link2};
function host(url:string){try{return new URL(url).hostname.replace(/^www\./,'');}catch{return 'Uploaded file';}}
function fileSize(n:number){return n>1024*1024?`${(n/1024/1024).toFixed(1)} MB`:`${Math.max(1,Math.round(n/1024))} KB`;}
async function api(path:string,init?:RequestInit){const response=await fetch(path,init);let data:{error?:string;items:Item[];item:Item};try{data=await response.json() as typeof data;}catch{throw new Error('Could not reach your archive. Please try again.');}if(!response.ok)throw new Error(data.error||'Could not save your changes.');return data;}
export default function Archive(){
 const [items,setItems]=useState<Item[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[tab,setTab]=useState('all'),[query,setQuery]=useState(''),[type,setType]=useState('all'),[collection,setCollection]=useState('all'),[quick,setQuick]=useState(''),[adding,setAdding]=useState(false),[selected,setSelected]=useState<Item|null>(null),[deleting,setDeleting]=useState(false),[deleteBusy,setDeleteBusy]=useState(false),[initialUrl,setInitialUrl]=useState('');
 async function refresh(){setLoading(true);setError('');try{const data=await api('/api/items');setItems(data.items);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{refresh();const p=new URLSearchParams(window.location.search);const shared=p.get('url')||'';if(shared){setInitialUrl(shared);setAdding(true);}},[]);
 const visible=useMemo(()=>items.filter(item=>(tab!=='inbox'||!item.destinations.length)&&(type==='all'||item.kind===type)&&(collection==='all'||item.destinations.includes(collection))&&query.toLowerCase().split(/\s+/).filter(Boolean).every(word=>[item.title,item.url,item.note,item.content,...item.tags,...item.destinations,item.kind].join(' ').toLowerCase().includes(word))),[items,tab,type,collection,query]);
 const inbox=items.filter(i=>!i.destinations.length).length;
 function openAdd(url=''){setInitialUrl(url);setAdding(true);}
 function saved(item:Item){setItems(old=>[item,...old.filter(i=>i.id!==item.id)].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)));setAdding(false);if(selected)setSelected(item);setQuick('');toast.success('Saved to your archive');}
 async function remove(){if(!selected)return;setDeleteBusy(true);try{await api('/api/items/'+selected.id,{method:'DELETE'});setItems(old=>old.filter(i=>i.id!==selected.id));setSelected(null);setDeleting(false);toast.success('Item deleted');}catch(e){toast.error((e as Error).message);}finally{setDeleteBusy(false);}}
 return <div className="app-shell">
  <Toaster position="bottom-center"/>
  <header className="topbar"><a className="brand" href="/" aria-label="Life Archive home"><span className="brand-icon"><ArchiveIcon size={22}/></span><span>life<span className="brand-light"> / archive</span></span></a><span className="private-label"><span className="lock-dot"/> Personal archive</span></header>
  <main className="workspace">
   <div className="heading-row"><div><p className="eyebrow">YOUR INTERNET, KEPT</p><h1>The good stuff.<br className="mobile-break"/> All here.</h1><p className="intro">Keep the things you want to come back to.</p></div><button className="primary add-top" onClick={()=>openAdd()}><Plus size={18}/> Save something</button></div>
   <form className="capture" onSubmit={e=>{e.preventDefault();openAdd(quick);}}><Link2 size={21}/><input type="url" aria-label="Link to save" placeholder="Paste a link worth keeping…" value={quick} onChange={e=>setQuick(e.target.value)}/><button className="capture-save" type="submit">Save link <ArrowUpRight size={17}/></button><span className="capture-divider"/><button className="upload-button" type="button" onClick={()=>openAdd()}><Upload size={18}/><span>Upload a file</span></button></form>
   <div className="capture-meta"><span>Links, GIFs, videos, memes, articles & more</span><span>Files up to 25 MB</span></div>
   <Tabs value={tab} onValueChange={setTab} className="archive-tabs"><div className="archive-toolbar"><TabsList variant="line" className="main-tabs"><TabsTrigger value="all"><ArchiveIcon/> Everything <span className="count">{items.length}</span></TabsTrigger><TabsTrigger value="inbox"><Inbox/> Inbox <span className="count">{inbox}</span></TabsTrigger></TabsList><span className="toolbar-note">One item. As many collections as it needs.</span></div>
    <div className="filter-bar"><div className="search-field"><Search size={18}/><input aria-label="Search archive" placeholder="Search titles, notes, tags…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="Clear search" onClick={()=>setQuery('')}><X size={16}/></button>}</div><div className="select-filters"><Select value={type} onValueChange={setType}><SelectTrigger aria-label="Filter by content type" className="filter-select"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All types</SelectItem>{kinds.map(k=><SelectItem key={k} value={k}>{k}</SelectItem>)}</SelectContent></Select><Select value={collection} onValueChange={setCollection}><SelectTrigger aria-label="Filter by collection" className="filter-select"><FolderOpen size={16}/><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All collections</SelectItem>{destinations.map(d=><SelectItem key={d} value={d}>{d}</SelectItem>)}</SelectContent></Select></div></div>
    {['all','inbox'].map(view=><TabsContent key={view} value={view}>
      {loading?<div className="item-grid" aria-label="Loading archive">{[1,2,3].map(n=><Skeleton className="h-64 rounded-xl" key={n}/>)}</div>:error?<div className="error-panel" role="alert"><h2>We couldn’t open your archive.</h2><p>{error}</p><button className="secondary" onClick={refresh}>Try again</button></div>:visible.length?<><div className="results-caption"><span>{visible.length} {visible.length===1?'item':'items'}{tab==='inbox'?' awaiting a collection':''}</span><span>Newest first</span></div><div className="item-grid">{visible.map(item=><ItemCard key={item.id} item={item} onOpen={()=>setSelected(item)}/>)}</div></>:<Empty className="archive-empty"><EmptyHeader><EmptyMedia><div className="empty-icon">{tab==='inbox'?<Inbox size={32}/>:<ArchiveIcon size={32}/>}</div></EmptyMedia><EmptyTitle className="empty-title">{items.length===0?'Your corner of the internet starts here.':query||type!=='all'||collection!=='all'?'No finds match these filters.':tab==='inbox'?'Everything has a home.':'Nothing here yet.'}</EmptyTitle><EmptyDescription className="empty-description">{items.length===0?'That article, that reaction GIF, that video you want to watch. Save your first find above.':tab==='inbox'&&!query&&type==='all'&&collection==='all'?'Items without a collection will wait here for you.':'Try another search or clear your filters.'}</EmptyDescription></EmptyHeader>{items.length===0?<button className="primary" onClick={()=>openAdd()}><Plus size={17}/> Save your first find</button>:(query||type!=='all'||collection!=='all')?<button className="secondary" onClick={()=>{setQuery('');setType('all');setCollection('all');}}>Clear filters</button>:null}</Empty>}
    </TabsContent>)}
   </Tabs>
   <footer className="archive-footer"><span><ArchiveIcon size={15}/> Saved files stay here. Bookmarks keep their source link.</span><span>life / archive</span></footer>
  </main>
  <Dialog open={adding} onOpenChange={setAdding}><DialogContent className="save-dialog"><DialogHeader><DialogTitle className="dialog-heading">Keep something good.</DialogTitle><DialogDescription>Add a link or a file. You can change its home anytime.</DialogDescription></DialogHeader><Editor key={initialUrl+'-'+adding} initialUrl={initialUrl} onSave={saved}/></DialogContent></Dialog>
  <Sheet open={!!selected} onOpenChange={open=>{if(!open)setSelected(null);}}><SheetContent className="detail-sheet"><SheetHeader><p className="eyebrow">SAVED FIND</p><SheetTitle className="detail-title">{selected?.title}</SheetTitle><SheetDescription>{selected?.hasFile?'File copy saved in your archive':'Bookmark only · original content is not downloaded'}</SheetDescription></SheetHeader>{selected&&<div className="detail-body"><Preview item={selected}/><div className="detail-links">{selected.url&&<a className="secondary" target="_blank" rel="noopener noreferrer" href={selected.url}>Open source <ArrowUpRight size={16}/></a>}{selected.hasFile&&<a className="secondary" href={'/api/items/'+selected.id+'/file?download=1'}>Download <Download size={16}/></a>}</div>{selected.hasFile&&<p className="small-muted">{selected.fileName} · {fileSize(selected.size)}</p>}<div className="detail-rule"/><Editor key={selected.id+selected.updatedAt} item={selected} onSave={saved}/><div className="detail-bottom"><span>Saved {new Date(selected.createdAt).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'})}</span><button className="danger-link" onClick={()=>setDeleting(true)}><Trash2 size={16}/> Delete</button></div></div>}</SheetContent></Sheet>
  <AlertDialog open={deleting} onOpenChange={setDeleting}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete this saved item?</AlertDialogTitle><AlertDialogDescription>The item and any uploaded file will be permanently removed from your archive.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={deleteBusy}>Keep it</AlertDialogCancel><AlertDialogAction disabled={deleteBusy} onClick={e=>{e.preventDefault();remove();}}>{deleteBusy?'Deleting…':'Delete item'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>;
}
function ItemCard({item,onOpen}:{item:Item;onOpen:()=>void}){const Icon=icons[item.kind]||Link2;return <button className="item-card" onClick={onOpen}><div className={'card-visual kind-'+item.kind.toLowerCase()}>{item.hasFile&&/^image\/(png|jpeg|gif|webp|avif)$/.test(item.mime||'')?<img loading="lazy" src={'/api/items/'+item.id+'/file'} alt={item.title}/>:<><Icon size={34} strokeWidth={1.4}/><span>{item.kind}</span></>}<span className="preservation">{item.hasFile?<><Check size={12}/> File saved</>:<><Link2 size={12}/> Bookmark</>}</span></div><div className="card-copy"><div className="card-source">{item.url?host(item.url):item.fileName}</div><h2>{item.title}</h2>{item.note&&<p>{item.note}</p>}<div className="card-collections">{item.destinations.length?item.destinations.map(d=><span key={d}>{d}</span>):<span className="inbox-tag">Inbox</span>}</div>{item.tags.length>0&&<div className="card-tags">{item.tags.slice(0,3).map(t=><span key={t}>#{t}</span>)}</div>}</div></button>;}
function Preview({item}:{item:Item}){const src='/api/items/'+item.id+'/file';if(!item.hasFile)return null;if(/^image\/(png|jpeg|gif|webp|avif)$/.test(item.mime||''))return <img className="file-preview" src={src} alt={item.title}/>;if(/^video\/(mp4|webm|quicktime)$/.test(item.mime||''))return <video className="file-preview" src={src} controls playsInline preload="metadata"/>;if(/^audio\/(mpeg|mp4|ogg|wav)$/.test(item.mime||''))return <audio className="audio-preview" src={src} controls preload="metadata"/>;if(item.content)return <pre className="text-preview">{item.content}</pre>;return <div className="document-preview"><FileText size={30}/><span>{item.fileName}</span></div>;}
function Editor({item,initialUrl='',onSave}:{item?:Item;initialUrl?:string;onSave:(item:Item)=>void}){
 const [url,setUrl]=useState(item?.url||initialUrl),[title,setTitle]=useState(item?.title||''),[kind,setKind]=useState(item?.kind||inferKind(initialUrl)),[note,setNote]=useState(item?.note||''),[tags,setTags]=useState(item?.tags.join(', ')||''),[file,setFile]=useState<File|null>(null),[manual,setManual]=useState(!!item),[homes,setHomes]=useState<string[]>(item?.destinations||[]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const fileInput=useRef<HTMLInputElement>(null);const suggestions=suggest(kind,[title,url,note,tags].join(' '));const chosen=manual?homes:suggestions;
 function changeUrl(value:string){setUrl(value);if(!item&&!file)setKind(inferKind(value));}
 async function submit(e:React.FormEvent){e.preventDefault();setError('');if(file&&file.size>25*1024*1024){setError('Choose a file of 25 MB or less.');return;}setBusy(true);try{const details={title:title.trim()||file?.name||url,kind,url,note,tags:tags.split(',').map(t=>t.trim()).filter(Boolean),destinations:chosen};let data;if(item){data=await api('/api/items/'+item.id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(details)});}else{const form=new FormData();form.set('details',JSON.stringify(details));if(file)form.set('file',file);data=await api('/api/items',{method:'POST',body:form});}onSave(data.item);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <form className="editor" onSubmit={submit}><fieldset disabled={busy} className="editor-fields"><label className="field"><span>Source link {file||item?.hasFile?<small>optional</small>:null}</span><input type="url" value={url} onChange={e=>changeUrl(e.target.value)} placeholder="https://…" maxLength={4000} required={!file&&!item?.hasFile}/></label>
 {!item&&<><input ref={fileInput} type="file" className="sr-only" aria-label="Choose a file to archive" onChange={e=>{const next=e.target.files?.[0]||null;setFile(next);if(next){if(!title)setTitle(next.name);setKind(inferKind(url,next.name,next.type));}}}/><button className={'file-picker '+(file?'has-file':'')} type="button" onClick={()=>fileInput.current?.click()}><Upload size={19}/><span>{file?file.name:'Or choose a file'}<small>{file?fileSize(file.size):'Images, GIFs, video, audio, documents · up to 25 MB'}</small></span></button>{file&&<button className="text-button" type="button" onClick={()=>{setFile(null);if(fileInput.current)fileInput.current.value='';setKind(inferKind(url));}}>Remove selected file</button>}</>}
 <div className="editor-two"><label className="field"><span>Title</span><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Give it a memorable name" maxLength={300}/></label><div className="field"><span id="type-label">Type</span><Select value={kind} onValueChange={setKind}><SelectTrigger aria-labelledby="type-label" className="editor-select"><SelectValue/></SelectTrigger><SelectContent>{kinds.map(k=><SelectItem value={k} key={k}>{k}</SelectItem>)}</SelectContent></Select></div></div>
 <label className="field"><span>Note <small>optional</small></span><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Why you’re keeping it, or words to find it later…" rows={2} maxLength={20000}/></label><label className="field"><span>Tags <small>separate with commas</small></span><input value={tags} onChange={e=>setTags(e.target.value)} placeholder="funny, family, philosophy…"/></label>
 <div className="routing"><div className="routing-title"><span><FolderOpen size={16}/> Collections</span><button className="text-button" type="button" onClick={()=>setManual(false)}>Use suggestions</button></div><div className="destination-options">{destinations.map(d=><label key={d} className={'destination-option '+(chosen.includes(d)?'checked':'')}><Checkbox checked={chosen.includes(d)} onCheckedChange={checked=>{setHomes(checked?[...chosen,d]:chosen.filter(x=>x!==d));setManual(true);}}/><span>{d}</span></label>)}</div><p className="small-muted">{manual?'Your selected collections.':suggestions.length?'Suggested from the type and words you entered.':'No clear match yet. This item will wait in your inbox.'} Collections are inside this archive.</p></div>
 {error&&<p className="form-error" role="alert">{error}</p>}<button className="primary save-item" type="submit" disabled={busy}>{busy?<Loader2 size={18} className="animate-spin"/>:<Check size={18}/>} {busy?'Saving…':item?'Save changes':'Save to archive'}</button><p className="save-note">{file||item?.hasFile?'A copy of your file is stored in your archive.':'This saves the link, title and notes. The webpage or video itself is not downloaded.'}</p></fieldset></form>;
}
