'use client';
import { useEffect, useState } from 'react';
import { Cloud, ExternalLink, Loader2 } from 'lucide-react';
import { toast } from 'sonner';
import { AlertDialog, AlertDialogContent, AlertDialogHeader, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogCancel, AlertDialogAction } from '@/components/ui/alert-dialog';
type Status={configured:boolean;connected:boolean;email:string|null;folderUrl:string|null};
export default function DriveConnection(){
 const [status,setStatus]=useState<Status|null>(null),[error,setError]=useState(''),[confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false);
 async function refresh(){try{setError('');const r=await fetch('/api/drive');const data=await r.json() as Status&{error?:string};if(!r.ok)throw new Error(data.error||'Connection status is unavailable.');setStatus(data);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{refresh();const q=new URLSearchParams(window.location.search);if(q.get('drive')==='connected')toast.success('Google Drive connected');if(q.get('drive_error'))toast.error(q.get('drive_error'));if(q.has('drive')||q.has('drive_error')){q.delete('drive');q.delete('drive_error');window.history.replaceState(null,'',window.location.pathname+(q.size?'?'+q:'')+window.location.hash);}},[]);
 async function disconnect(){setBusy(true);try{const r=await fetch('/api/drive',{method:'DELETE'});if(!r.ok)throw new Error('Could not disconnect Google Drive.');setConfirm(false);await refresh();toast.success('Disconnected. Your files remain in Google Drive.');}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
 return <section className="drive-connection" aria-label="Archive storage"><Cloud size={21}/><div className="drive-summary"><strong>Google Drive</strong><p>{error?error:!status?'Checking storage connection…':!status.configured?'Google Drive integration is awaiting setup.':status.connected?`Saving to Life Archive · ${status.email}`:'Connect your account to save new files and bookmarks.'}</p></div><div className="drive-actions">{error?<button className="secondary" onClick={refresh}>Try again</button>:status?.configured?<>{status.connected&&status.folderUrl&&<a className="secondary" href={status.folderUrl} target="_blank" rel="noopener noreferrer">Open folder <ExternalLink size={15}/></a>}<form action="/api/drive/connect" method="post" target="_top"><button className={status.connected?'secondary':'primary'} type="submit">{status.connected?'Reconnect':'Connect Google Drive'}</button></form>{status.connected&&<button className="text-button" onClick={()=>setConfirm(true)}>Disconnect</button>}</>:!status?<Loader2 size={18} className="animate-spin"/>:<span className="setup-pending">Setup needed</span>}</div><AlertDialog open={confirm} onOpenChange={setConfirm}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Disconnect Google Drive?</AlertDialogTitle><AlertDialogDescription>Your files stay in Google Drive. New saves and access to Drive files from this archive will pause until you reconnect. You can revoke the app’s Google permission separately in your Google Account settings.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>Keep connected</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();disconnect();}}>{busy?'Disconnecting…':'Disconnect'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></section>;
}
